### ISSUE TITLE
TypeError: Cannot read property 'write' of undefined ?

### ISSUE THREAD

**Issue by underwater** [FabianGosebrink/angular-face-recognition-api#1]
Great project, just tried to running project using ng serve -o and getting  below exception
Any suggestion ?

`Cannot read property 'write' of undefined
TypeError: Cannot read property 'write' of undefined
    at UI.write (C:\Repos\angular-face-recognition-api\node_modules\@angular\cli\ember-cli\lib\ui\index.js:56:23)
    at UI.writeLine (C:\Repos\angular-face-recognition-api\node_modules\@angular\cli\ember-cli\lib\ui\index.js:69:8)
    at Class.run (C:\Repos\angular-face-recognition-api\node_modules\@angular\cli\tasks\serve.js:237:12)
    at check_port_1.checkPort.then.port (C:\Repos\angular-face-recognition-api\node_modules\@angular\cli\commands\serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by sandy1198** [comment]
were i past the subscription key
